[program:pg-vip-api]
command=/var/www/services/pg-vip-api/venv/bin/gunicorn -w 2 -b 0.0.0.0:9022 --timeout 60 app:app
directory=/var/www/services/pg-vip-api
autostart=true
autorestart=true
stderr_logfile=/var/log/pg-vip-api.err.log
stdout_logfile=/var/log/pg-vip-api.out.log
environment=PYTHONUNBUFFERED="1"
